[2025-01-29T14:07:58.630+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_pipeline_intraday.start_producer_intraday manual__2025-01-29T14:07:53.939005+00:00 [queued]>
[2025-01-29T14:07:58.639+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_pipeline_intraday.start_producer_intraday manual__2025-01-29T14:07:53.939005+00:00 [queued]>
[2025-01-29T14:07:58.640+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-29T14:07:58.660+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): start_producer_intraday> on 2025-01-29 14:07:53.939005+00:00
[2025-01-29T14:07:58.664+0000] {standard_task_runner.py:57} INFO - Started process 58 to run task
[2025-01-29T14:07:58.670+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'stock_price_pipeline_intraday', 'start_producer_intraday', 'manual__2025-01-29T14:07:53.939005+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/stock_pipeline_dag.py', '--cfg-path', '/tmp/tmpag6rclyt']
[2025-01-29T14:07:58.672+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask start_producer_intraday
[2025-01-29T14:07:58.726+0000] {task_command.py:415} INFO - Running <TaskInstance: stock_price_pipeline_intraday.start_producer_intraday manual__2025-01-29T14:07:53.939005+00:00 [running]> on host d457ced5241c
[2025-01-29T14:07:59.323+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_price_pipeline_intraday' AIRFLOW_CTX_TASK_ID='start_producer_intraday' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T14:07:53.939005+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T14:07:53.939005+00:00'
[2025-01-29T14:07:59.324+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-29T14:07:59.325+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec producer-5min python kafka_producer_5min.py']
[2025-01-29T14:07:59.334+0000] {subprocess.py:86} INFO - Output:
[2025-01-29T14:07:59.910+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-01-29T14:07:59.911+0000] {subprocess.py:93} INFO - INFO:kafka.conn:Probing node bootstrap-0 broker version
[2025-01-29T14:07:59.912+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-01-29T14:08:00.016+0000] {subprocess.py:93} INFO - INFO:kafka.conn:Broker version identified as 2.5.0
[2025-01-29T14:08:00.018+0000] {subprocess.py:93} INFO - INFO:kafka.conn:Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2025-01-29T14:08:00.021+0000] {subprocess.py:93} INFO - INFO:__main__:Fetching data for symbol: AAPL
[2025-01-29T14:08:00.596+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-29T14:08:00.597+0000] {subprocess.py:93} INFO -   File "/app/kafka_producer_5min.py", line 94, in <module>
[2025-01-29T14:08:00.598+0000] {subprocess.py:93} INFO -     fetch_stock_data()
[2025-01-29T14:08:00.598+0000] {subprocess.py:93} INFO -   File "/app/kafka_producer_5min.py", line 80, in fetch_stock_data
[2025-01-29T14:08:00.599+0000] {subprocess.py:93} INFO -     if last_refreshed > last_update:
[2025-01-29T14:08:00.599+0000] {subprocess.py:93} INFO - TypeError: '>' not supported between instances of 'str' and 'NoneType'
[2025-01-29T14:08:00.600+0000] {subprocess.py:93} INFO - INFO:kafka.producer.kafka:Closing the Kafka producer with 0 secs timeout.
[2025-01-29T14:08:00.600+0000] {subprocess.py:93} INFO - INFO:kafka.producer.kafka:Proceeding to force close the producer since pending requests could not be completed within timeout 0.
[2025-01-29T14:08:00.640+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-29T14:08:00.650+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-29T14:08:00.655+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_pipeline_intraday, task_id=start_producer_intraday, execution_date=20250129T140753, start_date=20250129T140758, end_date=20250129T140800
[2025-01-29T14:08:00.672+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task start_producer_intraday (Bash command failed. The command returned a non-zero exit code 1.; 58)
[2025-01-29T14:08:00.695+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-29T14:08:00.718+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
