[2025-01-28T15:15:32.675+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_pipeline_intraday.start_consumer_intraday manual__2025-01-28T15:15:17.832591+00:00 [queued]>
[2025-01-28T15:15:32.682+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_pipeline_intraday.start_consumer_intraday manual__2025-01-28T15:15:17.832591+00:00 [queued]>
[2025-01-28T15:15:32.683+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-28T15:15:32.699+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): start_consumer_intraday> on 2025-01-28 15:15:17.832591+00:00
[2025-01-28T15:15:32.703+0000] {standard_task_runner.py:57} INFO - Started process 101 to run task
[2025-01-28T15:15:32.706+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'stock_price_pipeline_intraday', 'start_consumer_intraday', 'manual__2025-01-28T15:15:17.832591+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/stock_pipeline_dag.py', '--cfg-path', '/tmp/tmp3cw8fwu2']
[2025-01-28T15:15:32.708+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask start_consumer_intraday
[2025-01-28T15:15:32.753+0000] {task_command.py:415} INFO - Running <TaskInstance: stock_price_pipeline_intraday.start_consumer_intraday manual__2025-01-28T15:15:17.832591+00:00 [running]> on host ffc5ba868373
[2025-01-28T15:15:33.313+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_price_pipeline_intraday' AIRFLOW_CTX_TASK_ID='start_consumer_intraday' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T15:15:17.832591+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T15:15:17.832591+00:00'
[2025-01-28T15:15:33.314+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-28T15:15:33.315+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec consumer-5min python kafka_consumer_5min.py']
[2025-01-28T15:15:33.322+0000] {subprocess.py:86} INFO - Output:
[2025-01-28T15:15:34.895+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-01-28T15:15:34.895+0000] {subprocess.py:93} INFO - INFO:kafka.conn:Probing node bootstrap-0 broker version
[2025-01-28T15:15:34.896+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-01-28T15:15:35.001+0000] {subprocess.py:93} INFO - INFO:kafka.conn:Broker version identified as 2.5.0
[2025-01-28T15:15:35.002+0000] {subprocess.py:93} INFO - INFO:kafka.conn:Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2025-01-28T15:15:35.002+0000] {subprocess.py:93} INFO - INFO:kafka.consumer.subscription_state:Updating subscribed topics to: ('stock_prices_5min',)
[2025-01-28T15:15:35.258+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection node_id=1001 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-01-28T15:15:35.260+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection node_id=1001 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-01-28T15:15:35.262+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-01-28T15:15:36.330+0000] {subprocess.py:93} INFO - INFO:kafka.cluster:Group coordinator for stock_pipeline_5min is BrokerMetadata(nodeId='coordinator-1001', host='kafka', port=9092, rack=None)
[2025-01-28T15:15:36.332+0000] {subprocess.py:93} INFO - INFO:kafka.coordinator:Discovered coordinator coordinator-1001 for group stock_pipeline_5min
[2025-01-28T15:15:36.332+0000] {subprocess.py:93} INFO - INFO:kafka.coordinator:Starting new heartbeat thread
[2025-01-28T15:15:36.335+0000] {subprocess.py:93} INFO - INFO:kafka.coordinator.consumer:Revoking previously assigned partitions set() for group stock_pipeline_5min
[2025-01-28T15:15:36.336+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection node_id=coordinator-1001 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-01-28T15:15:36.336+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection node_id=coordinator-1001 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-01-28T15:15:36.438+0000] {subprocess.py:93} INFO - INFO:kafka.coordinator:(Re-)joining group stock_pipeline_5min
[2025-01-28T15:15:39.483+0000] {subprocess.py:93} INFO - INFO:kafka.coordinator:Elected group leader -- performing partition assignments using range
[2025-01-28T15:15:39.515+0000] {subprocess.py:93} INFO - INFO:kafka.coordinator:Successfully joined group stock_pipeline_5min with generation 1
[2025-01-28T15:15:39.516+0000] {subprocess.py:93} INFO - INFO:kafka.consumer.subscription_state:Updated partition assignment: [TopicPartition(topic='stock_prices_5min', partition=0)]
[2025-01-28T15:15:39.516+0000] {subprocess.py:93} INFO - INFO:kafka.coordinator.consumer:Setting newly assigned partitions {TopicPartition(topic='stock_prices_5min', partition=0)} for group stock_pipeline_5min
[2025-01-28T15:15:39.712+0000] {subprocess.py:93} INFO - INFO:kafka.coordinator:Stopping heartbeat thread
[2025-01-28T15:15:39.712+0000] {subprocess.py:93} INFO - INFO:kafka.coordinator:Leaving consumer group (stock_pipeline_5min).
[2025-01-28T15:15:39.728+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection node_id=1001 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-01-28T15:15:39.729+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection node_id=coordinator-1001 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection.
[2025-01-28T15:15:39.729+0000] {subprocess.py:93} INFO - INFO:__main__:Consumer closed.
[2025-01-28T15:15:39.730+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-28T15:15:39.730+0000] {subprocess.py:93} INFO -   File "/app/kafka_consumer_5min.py", line 34, in process_and_store
[2025-01-28T15:15:39.730+0000] {subprocess.py:93} INFO -     symbol = data.get("Meta Data").get("2. Symbol")
[2025-01-28T15:15:39.731+0000] {subprocess.py:93} INFO - AttributeError: 'NoneType' object has no attribute 'get'
[2025-01-28T15:15:39.731+0000] {subprocess.py:93} INFO - 
[2025-01-28T15:15:39.732+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2025-01-28T15:15:39.732+0000] {subprocess.py:93} INFO - 
[2025-01-28T15:15:39.732+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-28T15:15:39.735+0000] {subprocess.py:93} INFO -   File "/app/kafka_consumer_5min.py", line 101, in <module>
[2025-01-28T15:15:39.735+0000] {subprocess.py:93} INFO -     main()
[2025-01-28T15:15:39.736+0000] {subprocess.py:93} INFO -   File "/app/kafka_consumer_5min.py", line 90, in main
[2025-01-28T15:15:39.736+0000] {subprocess.py:93} INFO -     process_and_store(message.value)
[2025-01-28T15:15:39.736+0000] {subprocess.py:93} INFO -   File "/app/kafka_consumer_5min.py", line 75, in process_and_store
[2025-01-28T15:15:39.737+0000] {subprocess.py:93} INFO -     logger.error(f"Error processing data for {symbol}: {e}")
[2025-01-28T15:15:39.737+0000] {subprocess.py:93} INFO - UnboundLocalError: local variable 'symbol' referenced before assignment
[2025-01-28T15:15:39.855+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-28T15:15:39.863+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-28T15:15:39.866+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_pipeline_intraday, task_id=start_consumer_intraday, execution_date=20250128T151517, start_date=20250128T151532, end_date=20250128T151539
[2025-01-28T15:15:39.878+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task start_consumer_intraday (Bash command failed. The command returned a non-zero exit code 1.; 101)
[2025-01-28T15:15:39.910+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-28T15:15:39.927+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
