[2025-01-29T14:08:04.354+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_pipeline_daily.start_producer_daily manual__2025-01-29T14:07:55.852602+00:00 [queued]>
[2025-01-29T14:08:04.363+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_pipeline_daily.start_producer_daily manual__2025-01-29T14:07:55.852602+00:00 [queued]>
[2025-01-29T14:08:04.363+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-29T14:08:04.385+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): start_producer_daily> on 2025-01-29 14:07:55.852602+00:00
[2025-01-29T14:08:04.390+0000] {standard_task_runner.py:57} INFO - Started process 79 to run task
[2025-01-29T14:08:04.394+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'stock_price_pipeline_daily', 'start_producer_daily', 'manual__2025-01-29T14:07:55.852602+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/stock_pipeline_dag.py', '--cfg-path', '/tmp/tmp4aa7f5ej']
[2025-01-29T14:08:04.396+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask start_producer_daily
[2025-01-29T14:08:04.447+0000] {task_command.py:415} INFO - Running <TaskInstance: stock_price_pipeline_daily.start_producer_daily manual__2025-01-29T14:07:55.852602+00:00 [running]> on host d457ced5241c
[2025-01-29T14:08:05.008+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_price_pipeline_daily' AIRFLOW_CTX_TASK_ID='start_producer_daily' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T14:07:55.852602+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T14:07:55.852602+00:00'
[2025-01-29T14:08:05.009+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-29T14:08:05.010+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec producer-daily python kafka_producer_daily.py']
[2025-01-29T14:08:05.018+0000] {subprocess.py:86} INFO - Output:
[2025-01-29T14:08:05.411+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-01-29T14:08:05.412+0000] {subprocess.py:93} INFO - INFO:kafka.conn:Probing node bootstrap-0 broker version
[2025-01-29T14:08:05.412+0000] {subprocess.py:93} INFO - INFO:kafka.conn:<BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-01-29T14:08:05.518+0000] {subprocess.py:93} INFO - INFO:kafka.conn:Broker version identified as 2.5.0
[2025-01-29T14:08:05.519+0000] {subprocess.py:93} INFO - INFO:kafka.conn:Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2025-01-29T14:08:05.520+0000] {subprocess.py:93} INFO - INFO:__main__:Fetching data for symbol: AAPL
[2025-01-29T14:08:06.029+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-01-29T14:08:06.031+0000] {subprocess.py:93} INFO -   File "/app/kafka_producer_daily.py", line 92, in <module>
[2025-01-29T14:08:06.033+0000] {subprocess.py:93} INFO -     fetch_stock_data()
[2025-01-29T14:08:06.034+0000] {subprocess.py:93} INFO -   File "/app/kafka_producer_daily.py", line 78, in fetch_stock_data
[2025-01-29T14:08:06.034+0000] {subprocess.py:93} INFO -     if last_refreshed > last_update:
[2025-01-29T14:08:06.035+0000] {subprocess.py:93} INFO - TypeError: '>' not supported between instances of 'str' and 'NoneType'
[2025-01-29T14:08:06.035+0000] {subprocess.py:93} INFO - INFO:kafka.producer.kafka:Closing the Kafka producer with 0 secs timeout.
[2025-01-29T14:08:06.036+0000] {subprocess.py:93} INFO - INFO:kafka.producer.kafka:Proceeding to force close the producer since pending requests could not be completed within timeout 0.
[2025-01-29T14:08:06.086+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-01-29T14:08:06.097+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-29T14:08:06.104+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_pipeline_daily, task_id=start_producer_daily, execution_date=20250129T140755, start_date=20250129T140804, end_date=20250129T140806
[2025-01-29T14:08:06.125+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task start_producer_daily (Bash command failed. The command returned a non-zero exit code 1.; 79)
[2025-01-29T14:08:06.136+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-29T14:08:06.166+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
