[2025-01-27T15:11:32.452+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_pipeline_intraday.start_producer_intraday manual__2025-01-27T15:06:23.375284+00:00 [queued]>
[2025-01-27T15:11:32.459+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_pipeline_intraday.start_producer_intraday manual__2025-01-27T15:06:23.375284+00:00 [queued]>
[2025-01-27T15:11:32.460+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-01-27T15:11:32.481+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): start_producer_intraday> on 2025-01-27 15:06:23.375284+00:00
[2025-01-27T15:11:32.486+0000] {standard_task_runner.py:57} INFO - Started process 87 to run task
[2025-01-27T15:11:32.490+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'stock_price_pipeline_intraday', 'start_producer_intraday', 'manual__2025-01-27T15:06:23.375284+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/stock_pipeline_dag.py', '--cfg-path', '/tmp/tmpbysz46pp']
[2025-01-27T15:11:32.492+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask start_producer_intraday
[2025-01-27T15:11:32.538+0000] {task_command.py:415} INFO - Running <TaskInstance: stock_price_pipeline_intraday.start_producer_intraday manual__2025-01-27T15:06:23.375284+00:00 [running]> on host 3297853633a2
[2025-01-27T15:11:33.080+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_price_pipeline_intraday' AIRFLOW_CTX_TASK_ID='start_producer_intraday' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T15:06:23.375284+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-27T15:06:23.375284+00:00'
[2025-01-27T15:11:33.081+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-27T15:11:33.082+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec producer-5min python /opt/airflow/dags/producers/kafka_producer_5min.py']
[2025-01-27T15:11:33.090+0000] {subprocess.py:86} INFO - Output:
[2025-01-27T15:11:33.223+0000] {subprocess.py:93} INFO - python: can't open file '/opt/airflow/dags/producers/kafka_producer_5min.py': [Errno 2] No such file or directory
[2025-01-27T15:11:33.236+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-01-27T15:11:33.245+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-01-27T15:11:33.248+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=stock_price_pipeline_intraday, task_id=start_producer_intraday, execution_date=20250127T150623, start_date=20250127T151132, end_date=20250127T151133
[2025-01-27T15:11:33.264+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task start_producer_intraday (Bash command failed. The command returned a non-zero exit code 2.; 87)
[2025-01-27T15:11:33.283+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-27T15:11:33.309+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
